metadata:
  toc-title: "Table of Contents"
  mainfont: Carlito
toc: true
toc-depth: 3
to: docx
from: markdown-implicit_figures
number-sections: false
strip-comments: true
section-divs: true
highlight-style: haddock
verbosity: INFO
filters:
  - filters/fennel-loader.lua
